[project]
name = "pa-agent-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "langchain>=0.3.27",
    "streamlit>=1.50.0",
]
